name: Build latest ROMs

on:
  push:
    branches: [ "y1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_PATH: /usr/local/lib/android/sdk
      ANDROID_NDK_PATH: /home/runner/android-ndk-r10e
      ANDROID_NDK_ROOT: /home/runner/android-ndk-r10e

    steps:
    - uses: actions/checkout@v4
    
    - name: prepare build environment
      run: |
        sudo apt update
        sudo apt install lib32z1
        sudo apt install openjdk-17-jdk
        sudo apt install golang-go
        java --version
        cd android
        yes | ./installToolchain.sh
    
    - name: build go tools
      run: |
        mkdir android/build
        cd android/build
        export GOPATH=$PWD/go
        export CGO_ENABLED=0
        export GOOS=linux
        export GOARCH=arm
        export GOARM=6
        git clone https://github.com/rockbox-y1/gocurl.git 
        cd gocurl
        git checkout json-data
        go build -ldflags '-s -w' -o gocurl
        cd ..
        git clone https://codeberg.org/rockbox-y1/download-podcast.git
        cd download-podcast
        git checkout patches
        git clone https://github.com/rockbox-y1/id3-go.git
        cd id3-go
        git checkout patches
        cd ..
        go build -o poddl
    
    # Build 360p (Type A)
    - name: build 360p
      run: |
        cd android/build
        ../../tools/configure --target=201 --lcdwidth=480 --lcdheight=360 --type=n
        make clean
        make
        make classes
        make zip
        make unsigned-apk
        # Sign APK
        APKSIGNER=""
        if command -v apksigner >/dev/null 2>&1; then
            APKSIGNER="apksigner"
        elif [ -n "$ANDROID_SDK_PATH" ] && [ -f "$ANDROID_SDK_PATH/build-tools/$(ls -1 "$ANDROID_SDK_PATH/build-tools" | tail -1)/apksigner" ]; then
            APKSIGNER="$ANDROID_SDK_PATH/build-tools/$(ls -1 "$ANDROID_SDK_PATH/build-tools" | tail -1)/apksigner"
        fi
        $APKSIGNER sign --key ../platform.pk8 --cert ../platform.x509.pem rockbox_unsigned.apk
        cp rockbox_unsigned.apk rockbox_360p.apk
        cp -r libs libs_360p
    
    # Build 240p (Type A)
    - name: build 240p
      run: |
        cd android/build
        ../../tools/configure --target=201 --lcdwidth=320 --lcdheight=240 --type=n
        make clean
        make
        make classes
        make zip
        make unsigned-apk
        # Sign APK
        APKSIGNER=""
        if command -v apksigner >/dev/null 2>&1; then
            APKSIGNER="apksigner"
        elif [ -n "$ANDROID_SDK_PATH" ] && [ -f "$ANDROID_SDK_PATH/build-tools/$(ls -1 "$ANDROID_SDK_PATH/build-tools" | tail -1)/apksigner" ]; then
            APKSIGNER="$ANDROID_SDK_PATH/build-tools/$(ls -1 "$ANDROID_SDK_PATH/build-tools" | tail -1)/apksigner"
        fi
        $APKSIGNER sign --key ../platform.pk8 --cert ../platform.x509.pem rockbox_unsigned.apk
        cp rockbox_unsigned.apk rockbox_240p.apk
        cp -r libs libs_240p
      
    - name: bundle update.zip files
      run: |
        cd android/build
        # 360p Type A
        mkdir update_360p
        wget https://github.com/rockbox-y1/rockbox/releases/download/stock-menu/com.innioasis.y1_2.7.2.apk
        cp -r libs_360p update_360p/libs
        cp com.innioasis*.apk update_360p/.
        cp rockbox_360p.apk update_360p/rockbox.apk
        cp ../scripts/install-recovery.sh update_360p/.
        cp ../scripts/99Y1ButtonScript update_360p/.
        cp ../scripts/switch-to-stock.sh update_360p/.
        cp ../scripts/update.sh update_360p/.
        cp ../scripts/Rockbox.kl update_360p/.
        cp ../scripts/Stock.kl update_360p/.
        cp gocurl/gocurl update_360p/.
        cp download-podcast/poddl update_360p/.
        mv update_360p update
        zip -r update_360p.zip update/*
        rm -rf update
        
        # 240p Type A
        mkdir update_240p
        cp -r libs_240p update_240p/libs
        cp rockbox_240p.apk update_240p/rockbox.apk
        cp com.innioasis*.apk update_240p/.
        cp ../scripts/install-recovery.sh update_240p/.
        cp ../scripts/99Y1ButtonScript update_240p/.
        cp ../scripts/switch-to-stock.sh update_240p/.
        cp ../scripts/update.sh update_240p/.
        cp ../scripts/Rockbox.kl update_240p/.
        cp ../scripts/Stock.kl update_240p/.
        cp gocurl/gocurl update_240p/.
        cp download-podcast/poddl update_240p/.
        mv update_240p update
        zip -r update_240p.zip update/*
        rm -rf update

    - name: bundle ROMs
      run: |
        # 360p Type A
        mkdir base_360p
        cd base_360p
        wget https://github.com/rockbox-y1/rockbox/releases/download/type-a-base/rom.zip
        wget https://github.com/rockbox-y1/rockbox/releases/download/stock-menu/com.innioasis.y1_2.7.2.apk
        unzip rom.zip
        mkdir mount_sys
        mkdir mount_user
        sudo mount -t ext4 -o loop system.img mount_sys
        sudo mount -t ext4 -o loop userdata.img mount_user
        sudo cp com.innioasis.y1_2.7.2.apk mount_user/data/com.innioasis.y1.apk
        sudo cp ../android/scripts/LeanKeyKeyboardPro_v5.2.15_r.apk mount_user/data/LeanKeyKeyboardPro_v5.2.15_r.apk
        sudo cp ../android/build/rockbox_360p.apk mount_sys/app/org.rockbox.apk
        sudo chmod 644 mount_sys/app/org.rockbox.apk
        sudo chown root:root mount_sys/app/org.rockbox.apk
        sudo mkdir -p mount_sys/lib
        sudo cp ../android/build/libs_360p/armeabi/librockbox.so mount_sys/lib/.
        sudo chmod 644 mount_sys/lib/librockbox.so
        sudo chown root:root mount_sys/lib/librockbox.so
        sudo rm -rf mount_user/data/org.rockbox/lib
        sudo mkdir -p mount_user/data/org.rockbox/lib
        sudo cp ../android/build/libs_360p/armeabi/* mount_user/data/org.rockbox/lib/.
        sudo chmod 777 mount_user/data/org.rockbox/lib/*
        sudo mkdir -p mount_user/data/org.rockbox/app_rockbox/rockbox/docs
        sudo cp ../docs/COPYING mount_user/data/org.rockbox/app_rockbox/rockbox/docs/COPYING.txt
        sudo cp ../docs/LICENSES mount_user/data/org.rockbox/app_rockbox/rockbox/docs/LICENSES.txt
        unzip ../android/build/libs_360p/armeabi/libmisc.so
        for f in .rockbox/*; do
          sudo cp -rf "$f" mount_user/data/org.rockbox/app_rockbox/rockbox/
        done

        sudo cp ../android/scripts/install-recovery.sh mount_sys/etc/install-recovery.sh
        sudo chmod 755 mount_sys/etc/install-recovery.sh
        sudo mkdir -p mount_sys/etc/init.d
        sudo cp ../android/scripts/99Y1ButtonScript mount_sys/etc/init.d/
        sudo chmod 755 mount_sys/etc/init.d/99Y1ButtonScript
        sudo cp ../android/scripts/switch-to-stock.sh mount_user/data/

        sudo cp ../android/build/gocurl/gocurl mount_user/data
        sudo chmod 755 mount_user/data/gocurl
        sudo cp ../android/build/download-podcast/poddl mount_user/data
        sudo chmod 755 mount_user/data/poddl
        wget https://curl.se/ca/cacert.pem
        sudo cp cacert.pem mount_user/data

        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Rockbox.kl
        sudo cp ../android/scripts/Stock.kl mount_sys/usr/keylayout/Stock.kl
        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Generic.kl

        sudo mkdir -p mount_user/data/update
        sudo cp ../android/scripts/update.sh mount_user/data/update/update.sh

        sudo cp ../android/scripts/bootanimation.zip mount_sys/media/bootanimation.zip

        # Remove unneeded apps and services to save battery
        sudo rm mount_sys/app/YGPS.*
        sudo rm mount_sys/app/SmsReg.*
        sudo rm mount_sys/app/Phone.*
        sudo rm mount_sys/app/Nfc.*
        sudo rm mount_sys/app/CellConnService.*
        sudo rm mount_sys/app/MediaProvider.*
        sudo rm mount_sys/app/EngineerCode.*
        sudo rm mount_sys/app/EngineerMode.*
        sudo rm mount_sys/app/EngineerModeSim.*
        sudo rm mount_sys/lib/modules/ccci.ko
        sudo rm mount_sys/lib/modules/ccci_plat.ko
        sudo rm mount_sys/lib/modules/mtk_stp_gps.ko

        sudo umount mount_sys
        sudo umount mount_user
        rm rom.zip
        rm com.innioasis.y1_2.7.2.apk
        rm -r mount_sys
        rm -r mount_user
        rm -r .rockbox
        cd ../
        zip -j rom_360p.zip base_360p/*
        
        # 240p Type A
        mkdir base_240p
        cd base_240p
        wget https://github.com/rockbox-y1/rockbox/releases/download/type-a-base/rom.zip
        wget https://github.com/rockbox-y1/rockbox/releases/download/stock-menu/com.innioasis.y1_2.7.2.apk
        unzip rom.zip
        mkdir mount_sys
        mkdir mount_user
        sudo mount -t ext4 -o loop system.img mount_sys
        sudo mount -t ext4 -o loop userdata.img mount_user
        sudo cp com.innioasis.y1_2.7.2.apk mount_user/data/com.innioasis.y1.apk
        sudo cp ../android/scripts/LeanKeyKeyboardPro_v5.2.15_r.apk mount_user/data/LeanKeyKeyboardPro_v5.2.15_r.apk
        sudo cp ../android/build/rockbox_240p.apk mount_sys/app/org.rockbox.apk
        sudo chmod 644 mount_sys/app/org.rockbox.apk
        sudo chown root:root mount_sys/app/org.rockbox.apk
        sudo mkdir -p mount_sys/lib
        sudo cp ../android/build/libs/armeabi/librockbox.so mount_sys/lib/.
        sudo chmod 644 mount_sys/lib/librockbox.so
        sudo chown root:root mount_sys/lib/librockbox.so
        sudo rm -rf mount_user/data/org.rockbox/lib
        sudo mkdir -p mount_user/data/org.rockbox/lib
        sudo cp ../android/build/libs/armeabi/* mount_user/data/org.rockbox/lib/.
        sudo chmod 777 mount_user/data/org.rockbox/lib/*
        sudo mkdir -p mount_user/data/org.rockbox/app_rockbox/rockbox/docs
        sudo cp ../docs/COPYING mount_user/data/org.rockbox/app_rockbox/rockbox/docs/COPYING.txt
        sudo cp ../docs/LICENSES mount_user/data/org.rockbox/app_rockbox/rockbox/docs/LICENSES.txt
        unzip ../android/build/libs/armeabi/libmisc.so
        for f in .rockbox/*; do
          sudo cp -rf "$f" mount_user/data/org.rockbox/app_rockbox/rockbox/
        done

        sudo cp ../android/scripts/install-recovery.sh mount_sys/etc/install-recovery.sh
        sudo chmod 755 mount_sys/etc/install-recovery.sh
        sudo mkdir -p mount_sys/etc/init.d
        sudo cp ../android/scripts/99Y1ButtonScript mount_sys/etc/init.d/
        sudo chmod 755 mount_sys/etc/init.d/99Y1ButtonScript
        sudo cp ../android/scripts/switch-to-stock.sh mount_user/data/

        sudo cp ../android/build/gocurl/gocurl mount_user/data
        sudo chmod 755 mount_user/data/gocurl
        sudo cp ../android/build/download-podcast/poddl mount_user/data
        sudo chmod 755 mount_user/data/poddl
        wget https://curl.se/ca/cacert.pem
        sudo cp cacert.pem mount_user/data

        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Rockbox.kl
        sudo cp ../android/scripts/Stock.kl mount_sys/usr/keylayout/Stock.kl
        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Generic.kl

        sudo mkdir -p mount_user/data/update
        sudo cp ../android/scripts/update.sh mount_user/data/update/update.sh

        sudo cp ../android/scripts/bootanimation.zip mount_sys/media/bootanimation.zip

        # Remove unneeded apps and services to save battery
        sudo rm mount_sys/app/YGPS.*
        sudo rm mount_sys/app/SmsReg.*
        sudo rm mount_sys/app/Phone.*
        sudo rm mount_sys/app/Nfc.*
        sudo rm mount_sys/app/CellConnService.*
        sudo rm mount_sys/app/MediaProvider.*
        sudo rm mount_sys/app/EngineerCode.*
        sudo rm mount_sys/app/EngineerMode.*
        sudo rm mount_sys/app/EngineerModeSim.*
        sudo rm mount_sys/lib/modules/ccci.ko
        sudo rm mount_sys/lib/modules/ccci_plat.ko
        sudo rm mount_sys/lib/modules/mtk_stp_gps.ko

        sudo umount mount_sys
        sudo umount mount_user
        rm rom.zip
        rm com.innioasis.y1_2.7.2.apk
        rm -r mount_sys
        rm -r mount_user
        rm -r .rockbox
        cd ../
        zip -j rom_240p.zip base_240p/*
        
        # 360p Type B
        mkdir base_360p_type_b
        cd base_360p_type_b
        wget https://github.com/rockbox-y1/rockbox/releases/download/type-b-base/rom.zip
        wget https://github.com/rockbox-y1/rockbox/releases/download/stock-menu/com.innioasis.y1_2.7.2.apk
        unzip rom.zip
        mkdir mount_sys
        mkdir mount_user
        sudo mount -t ext4 -o loop system.img mount_sys
        sudo mount -t ext4 -o loop userdata.img mount_user
        sudo cp com.innioasis.y1_2.7.2.apk mount_user/data/com.innioasis.y1.apk
        sudo cp ../android/scripts/LeanKeyKeyboardPro_v5.2.15_r.apk mount_user/data/LeanKeyKeyboardPro_v5.2.15_r.apk
        sudo cp ../android/build/rockbox_360p.apk mount_sys/app/org.rockbox.apk
        sudo chmod 644 mount_sys/app/org.rockbox.apk
        sudo chown root:root mount_sys/app/org.rockbox.apk
        sudo mkdir -p mount_sys/lib
        sudo cp ../android/build/libs_360p/armeabi/librockbox.so mount_sys/lib/.
        sudo chmod 644 mount_sys/lib/librockbox.so
        sudo chown root:root mount_sys/lib/librockbox.so
        sudo rm -rf mount_user/data/org.rockbox/lib
        sudo mkdir -p mount_user/data/org.rockbox/lib
        sudo cp ../android/build/libs_360p/armeabi/* mount_user/data/org.rockbox/lib/.
        sudo chmod 777 mount_user/data/org.rockbox/lib/*
        sudo mkdir -p mount_user/data/org.rockbox/app_rockbox/rockbox/docs
        sudo cp ../docs/COPYING mount_user/data/org.rockbox/app_rockbox/rockbox/docs/COPYING.txt
        sudo cp ../docs/LICENSES mount_user/data/org.rockbox/app_rockbox/rockbox/docs/LICENSES.txt
        unzip ../android/build/libs_360p/armeabi/libmisc.so
        for f in .rockbox/*; do
          sudo cp -rf "$f" mount_user/data/org.rockbox/app_rockbox/rockbox/
        done

        sudo cp ../android/scripts/install-recovery.sh mount_sys/etc/install-recovery.sh
        sudo chmod 755 mount_sys/etc/install-recovery.sh
        sudo mkdir -p mount_sys/etc/init.d
        sudo cp ../android/scripts/99Y1ButtonScript mount_sys/etc/init.d/
        sudo chmod 755 mount_sys/etc/init.d/99Y1ButtonScript
        sudo cp ../android/scripts/switch-to-stock.sh mount_user/data/

        sudo cp ../android/build/gocurl/gocurl mount_user/data
        sudo chmod 755 mount_user/data/gocurl
        sudo cp ../android/build/download-podcast/poddl mount_user/data
        sudo chmod 755 mount_user/data/poddl
        wget https://curl.se/ca/cacert.pem
        sudo cp cacert.pem mount_user/data

        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Rockbox.kl
        sudo cp ../android/scripts/Stock.kl mount_sys/usr/keylayout/Stock.kl
        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Generic.kl

        sudo mkdir -p mount_user/data/update
        sudo cp ../android/scripts/update.sh mount_user/data/update/update.sh

        sudo cp ../android/scripts/bootanimation.zip mount_sys/media/bootanimation.zip

        # Remove unneeded apps and services to save battery
        sudo rm mount_sys/app/YGPS.*
        sudo rm mount_sys/app/SmsReg.*
        sudo rm mount_sys/app/Phone.*
        sudo rm mount_sys/app/Nfc.*
        sudo rm mount_sys/app/CellConnService.*
        sudo rm mount_sys/app/MediaProvider.*
        sudo rm mount_sys/app/EngineerCode.*
        sudo rm mount_sys/app/EngineerMode.*
        sudo rm mount_sys/app/EngineerModeSim.*
        sudo rm mount_sys/lib/modules/ccci.ko
        sudo rm mount_sys/lib/modules/ccci_plat.ko
        sudo rm mount_sys/lib/modules/mtk_stp_gps.ko

        sudo umount mount_sys
        sudo umount mount_user
        rm rom.zip
        rm com.innioasis.y1_2.7.2.apk
        rm -r mount_sys
        rm -r mount_user
        rm -r .rockbox
        cd ../
        zip -j rom_360p_type_b.zip base_360p_type_b/*
        
        # 240p Type B
        mkdir base_240p_type_b
        cd base_240p_type_b
        wget https://github.com/rockbox-y1/rockbox/releases/download/type-b-base/rom.zip
        wget https://github.com/rockbox-y1/rockbox/releases/download/stock-menu/com.innioasis.y1_2.7.2.apk
        unzip rom.zip
        mkdir mount_sys
        mkdir mount_user
        sudo mount -t ext4 -o loop system.img mount_sys
        sudo mount -t ext4 -o loop userdata.img mount_user
        sudo cp com.innioasis.y1_2.7.2.apk mount_user/data/com.innioasis.y1.apk
        sudo cp ../android/scripts/LeanKeyKeyboardPro_v5.2.15_r.apk mount_user/data/LeanKeyKeyboardPro_v5.2.15_r.apk
        sudo cp ../android/build/rockbox_240p.apk mount_sys/app/org.rockbox.apk
        sudo chmod 644 mount_sys/app/org.rockbox.apk
        sudo chown root:root mount_sys/app/org.rockbox.apk
        sudo mkdir -p mount_sys/lib
        sudo cp ../android/build/libs_240p/armeabi/librockbox.so mount_sys/lib/.
        sudo chmod 644 mount_sys/lib/librockbox.so
        sudo chown root:root mount_sys/lib/librockbox.so
        sudo rm -rf mount_user/data/org.rockbox/lib
        sudo mkdir -p mount_user/data/org.rockbox/lib
        sudo cp ../android/build/libs_240p/armeabi/* mount_user/data/org.rockbox/lib/.
        sudo chmod 777 mount_user/data/org.rockbox/lib/*
        sudo mkdir -p mount_user/data/org.rockbox/app_rockbox/rockbox/docs
        sudo cp ../docs/COPYING mount_user/data/org.rockbox/app_rockbox/rockbox/docs/COPYING.txt
        sudo cp ../docs/LICENSES mount_user/data/org.rockbox/app_rockbox/rockbox/docs/LICENSES.txt
        unzip ../android/build/libs_240p/armeabi/libmisc.so
        for f in .rockbox/*; do
          sudo cp -rf "$f" mount_user/data/org.rockbox/app_rockbox/rockbox/
        done

        sudo cp ../android/scripts/install-recovery.sh mount_sys/etc/install-recovery.sh
        sudo chmod 755 mount_sys/etc/install-recovery.sh
        sudo mkdir -p mount_sys/etc/init.d
        sudo cp ../android/scripts/99Y1ButtonScript mount_sys/etc/init.d/
        sudo chmod 755 mount_sys/etc/init.d/99Y1ButtonScript
        sudo cp ../android/scripts/switch-to-stock.sh mount_user/data/

        sudo cp ../android/build/gocurl/gocurl mount_user/data
        sudo chmod 755 mount_user/data/gocurl
        sudo cp ../android/build/download-podcast/poddl mount_user/data
        sudo chmod 755 mount_user/data/poddl
        wget https://curl.se/ca/cacert.pem
        sudo cp cacert.pem mount_user/data

        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Rockbox.kl
        sudo cp ../android/scripts/Stock.kl mount_sys/usr/keylayout/Stock.kl
        sudo cp ../android/scripts/Rockbox.kl mount_sys/usr/keylayout/Generic.kl

        sudo mkdir -p mount_user/data/update
        sudo cp ../android/scripts/update.sh mount_user/data/update/update.sh

        sudo cp ../android/scripts/bootanimation.zip mount_sys/media/bootanimation.zip

        # Remove unneeded apps and services to save battery
        sudo rm mount_sys/app/YGPS.*
        sudo rm mount_sys/app/SmsReg.*
        sudo rm mount_sys/app/Phone.*
        sudo rm mount_sys/app/Nfc.*
        sudo rm mount_sys/app/CellConnService.*
        sudo rm mount_sys/app/MediaProvider.*
        sudo rm mount_sys/app/EngineerCode.*
        sudo rm mount_sys/app/EngineerMode.*
        sudo rm mount_sys/app/EngineerModeSim.*
        sudo rm mount_sys/lib/modules/ccci.ko
        sudo rm mount_sys/lib/modules/ccci_plat.ko
        sudo rm mount_sys/lib/modules/mtk_stp_gps.ko

        sudo umount mount_sys
        sudo umount mount_user
        rm rom.zip
        rm com.innioasis.y1_2.7.2.apk
        rm -r mount_sys
        rm -r mount_user
        rm -r .rockbox
        cd ../
        zip -j rom_240p_type_b.zip base_240p_type_b/*
    
    # Set release date
    - name: Set release date
      id: date
      run: echo "release_date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT
    
    # Create single release
    - name: create release
      id: create_release
      uses: shogo82148/actions-create-release@v1
      with:
        release_name: Rockbox-Y1 Nightly-${{ steps.date.outputs.release_date }}
        tag_name: nightly-${{ github.sha }}
        prerelease: false
        make_latest: true
    
    # Upload all assets to single release
    - name: upload 360p APK
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/rockbox_360p.apk
        asset_name: rockbox_360p.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: upload 240p APK
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/rockbox_240p.apk
        asset_name: rockbox_240p.apk
        asset_content_type: application/vnd.android.package-archive

    - name: upload update_360p.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/update_360p.zip
        asset_name: update_360p.zip
        asset_content_type: application/zip
    
    - name: upload update_240p.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/update_240p.zip
        asset_name: update_240p.zip
        asset_content_type: application/zip
    
    - name: upload update_360p_type_b.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/update_360p_type_b.zip
        asset_name: update_360p_type_b.zip
        asset_content_type: application/zip
    
    - name: upload update_240p_type_b.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./android/build/update_240p_type_b.zip
        asset_name: update_240p_type_b.zip
        asset_content_type: application/zip
    
    - name: upload rom_360p.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rom_360p.zip
        asset_name: rom_360p.zip
        asset_content_type: application/zip
    
    - name: upload rom_240p.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rom_240p.zip
        asset_name: rom_240p.zip
        asset_content_type: application/zip
    
    - name: upload rom_360p_type_b.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rom_360p_type_b.zip
        asset_name: rom_360p_type_b.zip
        asset_content_type: application/zip
    
    - name: upload rom_240p_type_b.zip
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rom_240p_type_b.zip
        asset_name: rom_240p_type_b.zip
        asset_content_type: application/zip
